name = "softbuydeals"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "softbuydeals"
database_id = "d202ba02-c82a-4acb-b412-1cb39382d8b9"

[ai]
binding = "AI"

routes = [
  { pattern = "softbuydeals.in", custom_domain = true },
  { pattern = "www.softbuydeals.in", custom_domain = true },
]

